# SPDX-License-Identifier: Apache-2.0
description: PMW3610 Trackball Sensor
compatible: "pixart,pmw3610"

properties:
  reg:
    type: int
    required: true
    description: "SPI chip select number"

  spi-max-frequency:
    type: int
    required: false
    default: 2000000
    description: "Maximum SPI frequency"

  irq-gpios:
    type: phandle-array
    required: false
    description: "Interrupt pin"

  scroll-layers:
    type: int
    required: false
    description: "Layer to activate scroll mode"

  automouse-layer:
    type: int
    required: false
    description: "Layer to activate auto-mouse mode"
