manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: yangxing
      url-base: https://github.com/yangxing844
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    - name: zmk-lpm009m360a-driver
      remote: yangxing
      revision: master
    - name: custom_mouse
      path: config/modules/custom_mouse
      revision: main
  self:
    path: config
    west-commands: config/west-commands.yml  # カスタムモジュールのコマンドを定義
  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk.git
      revision: main
      import: app
